### ISSUE TITLE
Generate an ai image for the background

### ISSUE THREAD

**Issue by anthony-devarti** [anthony-devarti/sylvan-library#23]
the image that we're using is not a good one.

we should generate an ai image for now, even in development, I'm not a fan of uncredited art.

Some things about the image:
it should be evocative of the card: sylvan library
it should be predominantly green
the center of the image should be darker
the image should not have any necessary focal points in the center in order to make sense that may be covered up

**Comment by ast-epk** [comment]
I'm testing out some work in Stable Diffusion right now, I'm going to try using the ["Vixon's Fantasy Mix" model](https://civitai.com/models/234898/vixons-fantasy-mix) to generate a forest background and maybe edit the colors a bit if necessary.

**Comment by ast-epk** [comment]
Replaced image with new AI generated image attached.

![sylvan-library-colorfix](https://github.com/anthony-devarti/sylvan-library/assets/75808715/f0df4aeb-24a1-4088-aec4-db8e80db7f5b)

Updated `sylvan-library/sylvan-library/src/Styles/Pages/_home.scss` and `sylvan-library/sylvan-library/src/Styles/style.css` with new reference links to image.
