### ISSUE TITLE
Adding an item to basket, generates a lineitem entry in the db

### ISSUE THREAD

**Issue by anthony-devarti** [anthony-devarti/sylvan-library#8]
when a user clicks reserve to add to basket, POST to lineitem

The item should be marked as reserved:true

the item will be marked as reserved:false when:

If the user removes it from their basket
the user times out/basket is cleared
when the reservation is marked as "complete"

**Comment by ast-epk** [comment]
> The item should be marked as reserved:true
> the item will be marked as reserved:false when:

See Issue #9 for the updated field on lineitem

**Comment by anthony-devarti** [comment]
Currently, an item is being marked as hold=true when it is added to the basket, and there's even a nice toast setup done as well.
The search results are NOT being updated, but I would like to attempt to merge this as is and address that in another ticket.
